MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (32, 64, 96, 128, 192)
    ANCHOR_STRIDE: (8,)
  ROI_BOX_HEAD:
    POOLER_SCALES: (1.0/8,)
    NUM_CLASSES: 9
  RESNETS:
    STEM_FUNC: StemWithFixedBatchNormWOPooling
DATASETS:
  TRAIN: ("occluded_linemod_train", )
  TEST: ("occluded_linemod_val",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, 105000)
  MAX_ITER: 120000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 4
OUTPUT_DIR: ./output/occluded_linemod/e2e_faster_rcnn_RwoPooling_50_C4_1x_2gpu
