MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (32, 64, 96, 128, 192)
  ROI_BOX_HEAD:
    NUM_CLASSES: 9
DATASETS:
  TRAIN: ("occluded_linemod_train", )
  TEST: ("occluded_linemod_val",)
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, 52500)
  MAX_ITER: 60000
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 4
OUTPUT_DIR: ./output/occluded_linemod/e2e_faster_rcnn_R_50_C4_1x_4gpu
